### PR TITLE
feat(): show old version of hunks via virtual lines

### PR DESCRIPTION
**Pull request by lewis6991**
Use virtual lines to show the old version of hunks inline in the buffer.

- Added config.show_deleted
- Added toggle_deleted()

E.g:

image

### CODE REVIEW

**Comment by gegoune** [comment]
Oh wow! That's a neat idea!

**Comment by gegoune** [comment]
Is highlight group configurable?

**Comment by lewis6991** [comment]
Not yet, currently uses `GitSignDeleteLn`.

**Comment by gegoune** [comment]
A, I saw TermCursor and assumed it's only that, but if it is a custom group then colorschemes can just style it accordingly, doesn't need to be configurable as can just be linked if needed.

**Comment by lewis6991** [comment]
Yep, I sorting out highlights more with #395

**Comment by WhyNotHugo** [comment]
I was looking for exactly this, thanks! :beer:

**Pull request merged**
