### PR TITLE
Adds cursor position to the jump list before `next_hunk` and `prev_hunk`

### LINKED ISSUE #412: Add cursor position to the jump list before `next_hunk` and `prev_hunk`
At the moment these two functions do not add the cursor location to the jump list.
As someone who uses often the jump list, I think that it would be very useful to have this feature.

### PR DESCRIPTION
**Pull request by mroavi**
Fixes #412

### CODE REVIEW

**Comment by lewis6991** [comment]
Please read CONTRIBUTING.md

**Comment by mroavi** [comment]
Ah Sorry. Let me take a look.

**Comment by mroavi** [comment]
I modified the teal source files and compiled them with `make tl-build`. Let me know if I'm missing something else.

**Comment by lewis6991** [comment]
Thanks!

**Pull request merged**
