### PR TITLE
fix: use documented highlight groups as fallback

### PR DESCRIPTION
**Pull request by seblj**
I don't know if you will accept this or not, but I'll give it a go.

I changed one of the fallback highlight groups from `diffAdded`, `diffChanged`, `diffRemoved`, to `Added`, `Changed`, and `Removed`.

The reason for changing this, is because by default, without any changes in any colorscheme, the highlight groups with `diff` prefixed, is not documented in the help docs of neovim. At least not in `syntax.txt` nor when using helpgrep to search for them.

The second argument is that `diffAdded`, `diffChanged` and `diffRemoved` are only set in `syntax/diff.vim` by default. Also, when they are set in `syntax/diff.vim`, they are all linked to the highlight groups I have changed to in this PR

I'll include some screenshots when using the new default colorscheme with the newest version of neovim compiled today. I used the minimal config on your issue tracker, and only changing it to use my fork and branch on the `after` picture

## Before:

image

## After:

image

### CODE REVIEW

**Comment by seblj** [comment]
I see that the tests are failing. Let me know if this is something that you would be willing to accept or not. If so, I'll update the tests

**Comment by lewis6991** [comment]
Nightly tests are broken atm, haven't debugged why.

**Comment by seblj** [comment]
Yes, I just ran the minimal config on your issue tracker like this

```lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

**Comment by lewis6991** [comment]
Awesome. Thanks a lot. Will fix the tests later.

**Comment by seblj** [comment]
No problem!

**Pull request merged**
