### PR TITLE
feat!: change default of attached_to_untracked to false

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by jwhitley** [comment]
FYI, this changed a default, but didn't update the default for attached_to_untracked in README.md (still says true).

**Comment by lewis6991** [comment]
Look at the contents of the PR

**Comment by bew** [comment]
I'm curious, what's the reasoning behind this change of default? (if there is one)

**Comment by lewis6991** [comment]
I got feedback from multiple people that they hated it and I understood their reasoning. Fwiw I'll still continue to use it.

**Pull request merged**
