### PR TITLE
staged signs (take 2)

### PR DESCRIPTION
**Pull request by lewis6991**
Example: second hunk in the screenshot is staged:

Screenshot 2022-04-18 at 21 54 53

### CODE REVIEW

**Comment by lewis6991** [comment]
Behaviour of this is a bit wonky in places, but going to submit this as a *hidden* feature that *can* be enabled with `config._signs_staged_enable = true`.

**Comment by rockyzhang24** [comment]
Great enhancement 👍
Do you consider to make `preview_hunk` work in the staged hunk as well?

**Comment by lewis6991** [comment]
Haven't considered it but it sounds like a good idea!

**Comment by lewis6991** [comment]
I've added support for most actions that made sense. Let me know if any are missing.

**Comment by clason** [comment]
Docs are missing ;)

**Comment by lewis6991** [comment]
Still a hidden feature. Docs will become visible when the `_` prefix is removed from the config entries.

**Comment by clason** [comment]
Sure; I meant here for people interested in testing it out.

**Pull request merged**
