### PR TITLE
fix: Change awrap to wrap in diffthis.lua

### PR DESCRIPTION
**Pull request by setibeings**
Addresses https://github.com/lewis6991/gitsigns.nvim/issues/857

### CODE REVIEW

**Comment by lewis6991** [comment]
Thanks. Make the commit linter happy and I'll merge.

**Comment by setibeings** [comment]
What's the process here? Do I amend the commit, then force push, or do you use the pull request title in cases where multiple commits will get squashed?

**Comment by lewis6991** [comment]
Amend and force push

**Comment by setibeings** [comment]
it's pushed now.

**Pull request merged**
