### PR TITLE
Add multiline blame in visual mode

### PR DESCRIPTION
**Pull request by Fabian-programmer**
A solution for multiline blaming in visual mode, see:
https://github.com/lewis6991/gitsigns.nvim/issues/390

The diff looks wild, because I ran the lua formatter over it. If this feature is wished, I can do a minimalistic diff with doc, etc...

For the visual blame i use the current selected line numbers as id's for extmark. I'm a lua/nvim beginner, so i bet there are a lot of improvements.

To navigate look at following functions:
```
visual_selection_range()
reset(bufnr, mode)
and update
```

grafik

### CODE REVIEW

**Comment by lewis6991** [comment]
Gitsigns is implemented in teal. See CONTRIBUTING.md

**Comment by Fabian-programmer** [comment]
@lewis6991 ported to teal.

**Comment by lewis6991** [comment]
I'm not too sure about this. It makes any general use of visual mode much more noisy. 

I think if we were to implement multi-line blame then I'd prefer to do something more similar to fugitives `Git blame` which I think is a lot more useful since it:
- aligns all the blames
- color codes them
- applies to all lines

**Comment by Fabian-programmer** [comment]
> I'm not too sure about this. It makes any general use of 
> visual` mode much more noisy.

Or you have to opt-in with a config parameter to enable the feature.
but yes multiline blame like fugitive would suffice for me too :)

**Comment by Drowze** [comment]
Personally I do like the idea as an opt-in feature :)

And I also agree about fugitive's `G blame` - it's one of the few killer features from fugitive for me (along with `G Browse`).

**Comment by lewis6991** [comment]
On reflection, this isn't something I wish to maintain.

At some point I'll come up with a solution that will reduce the need for `:G blame`.

**Pull request closed without merging**
