### PR TITLE
fix(update): always update file info when refreshing compare text

### LINKED ISSUE #847: Assertion failed in coroutine
### Description

This is very similar to https://github.com/lewis6991/gitsigns.nvim/issues/814, but happening in a slightly different part of `hunks.lua`.

I can't work out quite _when_ this crash happens, but I've found it to happen pretty consistently in a Python file that is open for a minute or so. Of course when the error shows, the git signs completely vanish.

---

I had a run through the `hunks.lua` file and found the `assert` thats failing. I commented it out and had a play around with the minimum config again and that seems to do the job, but I can't be sure that's not _absolutely_ required in the plugin.

### Neovim version

nightly

### Operating system and version

debian

### Expected behavior

_No response_

### Actual behavior

Error output is the following;
```
Error executing vim.schedule lua callback: ...gitsigns_issue/gitsigns//lua/gitsigns/async.lua:76: The coroutine failed with this message: ...gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...gitsigns_issue/gitsigns//lua/gitsigns/hunks.lua:172: in function 'calc_signs'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:59: in function 'apply_win_signs0'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:81: in function 'apply_win_signs'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:454: in function 'fn'
        ...tform/gitsigns_issue/gitsigns//lua/gitsigns/debounce.lua:76: in function 'update'
        ...gitsigns_issue/gitsigns//lua/gitsigns/watcher.lua:88: in function <...gitsigns_issue/gitsigns//lua/gitsigns/watcher.lua:59>
stack traceback:
        [C]: in function 'error'
        ...gitsigns_issue/gitsigns//lua/gitsigns/async.lua:76: in function 'cb'
        ...gitsigns_issue/gitsigns//lua/gitsigns/async.lua:113: in function 'cb'
        ...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:36: in function <...gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:34>
```

### Minimal config

```Lua
for name, url in pairs({
	gitsigns = "https://github.com/lewis6991/gitsigns.nvim",
	-- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
	nvim_lspconfig = "https://github.com/neovim/nvim-lspconfig",
}) do
	local install_path = vim.fn.fnamemodify("gitsigns_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

require("gitsigns").setup({
	debug_mode = true, -- You must add this to enable debug messages
	-- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
})

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE

require("lspconfig").pyright.setup({})
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Wait for a little bit

### Gitsigns debug messages

_No response_

### PR DESCRIPTION
**Pull request by lewis6991**
Fixes #847

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
unfortunately i already reproduced the error even with this version..

```
Error executing vim.schedule lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/hunks.lua:174: Invalid hunk with untracked=true hunk="@@ -25,1 +25,1 @@"
stack traceback:
	[C]: in function 'assert'
	...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/hunks.lua:174: in function 'calc_signs'
	...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:52: in function 'apply_win_signs0'
	...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:76: in function 'apply_win_signs'
	...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:517: in function 'fn'
	...ack/packer/start/gitsigns.nvim/lua/gitsigns/debounce.lua:68: in function 'update'
	...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:101: in function <...pack/packer/start/gitsigns.nvim/lua/gitsigns/watcher.lua:63>
stack traceback:
	[C]: in function 'error'
	...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb'
	...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:127: in function <...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:126>
	[C]: in function 'resume'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:193: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:247: in function 'notify_all'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:222: in function 'step'
	...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:399: in function <...e/pack/packer/start/diffview.nvim/lua/diffview/async.lua:391>
```

i do believe it's related to how slow neovim is. right now i'm making a big port, the lsp is very slow, many build errors and so on.

this was again from diffview.

**Comment by lewis6991** [comment]
I've significantly reworked this, so the buffer contents come from the direct git object as opposed to running the more abtract `git show <revision>:<path>` command. This should ensure the buffer contents always matches the tracked object name, even if it's not up-to-date because of other processes.

**Comment by lewis6991** [comment]
@emmanueltouzery have you had a chance to test this?

**Comment by emmanueltouzery** [comment]
yes, I'm using it. I did not reproduce the issue since switching to it. However I have finished my huge refactor and I'm less likely to reproduce the issue right now. Even before this refactor I would reproduce the issue regularly, but not as readily. Maybe once per week, give or take. I intend to stay on the branch and report if I reproduce the issue again.

**Comment by lewis6991** [comment]
> However I have finished my huge refactor and I'm less likely to reproduce the issue right now. 

Even with your system being pushed with so many git operations, gitsigns shouldn't error. What's useful about your situation is that you can reproduce this issue much more easily than others.

**Comment by lewis6991** [comment]
@emmanueltouzery any updates? Have you been able to test this any more?

**Comment by emmanueltouzery** [comment]
i'm using this branch all the time. i didn't reproduce the issue anymore, but it's true that i'm not having the extreme temporary situation that i had back then. on the other hand, i had been reproducing the issue like once every 10 days at least before, and i haven't seen it yet on this branch.

**Comment by lewis6991** [comment]
Thanks for letting me know. I guess we can merge this.

**Pull request merged**
