### PR TITLE
break!: deprecate config.keymaps

### PR DESCRIPTION
**Pull request by lewis6991**
- Removed default keymappings.
- Instead on_attach should be used.

### CODE REVIEW

**Comment by gegoune** [comment]
Out of interest, what's the reasoning behind that decision?

**Comment by lewis6991** [comment]
In short:
- I've disliked the keymaps have been handled ever since I created the plugin.
- Using `on_attach` allows us to remove a whole module within gitsigns and simplifies the init process.
- Using `on_attach` is around the same amount of code but more flexible/versatile and can be better linted/checked if using an LSP or luacheck.
- I don't really see a benefit in the current declarative approach.

Do you have any opinions?

**Comment by gegoune** [comment]
No, not at all noisy genuinely was interested in your idea behind that change. Not a big change, especially with provided example. Whatever makes sense for you. Thanks for taking time to write back!

**Comment by wookayin** [comment]
I think relying on `vim.keymap.set` (neovim 0.7.0+ API) is a bit too early to have. I didn't want to use the APIs that are only available in nightly versions, so I managed to make keymap configs that would work with neovim 0.6.x as follows:

```lua
gitsigns.setup {

  on_attach = function(bufnr)
    local function map(mode, lhs, rhs, opts)
        opts = vim.tbl_extend('force', {noremap = true, silent = false}, opts or {})
        vim.api.nvim_buf_set_keymap(bufnr, mode, lhs, rhs, opts)
    end
    map('n', ']c', "&diff ? ']c' : '<cmd>Gitsigns next_hunk<CR>'", {expr=true})
    map('n', '[c', "&diff ? '[c' : '<cmd>Gitsigns prev_hunk<CR>'", {expr=true})
    map('n', '<leader>hs', '<cmd>Gitsigns stage_hunk<CR>')
    map('n', '<leader>hr', '<cmd>Gitsigns reset_hunk<CR>')
    map('v', '<leader>hs', '<cmd>Gitsigns stage_hunk<CR>')
    map('v', '<leader>hr', '<cmd>Gitsigns reset_hunk<CR>')
    map('n', '<leader>hS', '<cmd>Gitsigns stage_buffer<CR>')
    map('n', '<leader>hu', '<cmd>Gitsigns undo_stage_hunk<CR>')
    map('n', '<leader>hR', '<cmd>Gitsigns reset_buffer<CR>')
    map('n', '<leader>hp', '<cmd>Gitsigns preview_hunk<CR>')
    map('n', '<leader>hb', '<cmd>lua require"gitsigns".blame_line {full=true, ignore_whitespace=true}<CR>')
    map('n', '<leader>tb', '<cmd>Gitsigns toggle_current_line_blame<CR>')
    map('n', '<leader>hd', '<cmd>Gitsigns diffthis<CR>')
    map('n', '<leader>hD', '<cmd>lua require"gitsigns".diffthis("~")<CR>')
    map('n', '<leader>td', '<cmd>Gitsigns toggle_deleted<CR>')
  end

}
```

**Comment by lewis6991** [comment]
Thanks. I'll add this to the readme.

**Pull request merged**
