### PR TITLE
Add secondary set of signs

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by weilbith** [comment]
This feature reads nice! Looking forward to use it. :upside_down_face:

**Comment by lewis6991** [comment]
How about testing it and providing feedback 😉 ?

I've been dogfooding this for a week or two and works well enough to use.

I'm not totally happy about the design of the new configuration. Feels a little overwhelming to users but once configured correctly is really nice to use.

**Comment by weilbith** [comment]
In regards of the configuration: I never use three parts of Lua plugin configurations: mappings, highlights and signs. So I do for this plugin. So maybe the configuration would be just fine for me. I need to checkout your changes in more details again. With my current minimal knowledge of this feature I would setup it like this (with comparison to my "normal" signs):

```vim
sign define GitSignsAdd            text=▌ texthl=GreenBold  numhl=Green
sign define GitSignsAddStaged text=│ texthl=GrennBold
```

So in fact make it just less prominent and just have it as a weak hint remaining. Let's see. I'll try it. 😬

**Comment by weilbith** [comment]
Okay, I discovered the following issue:
- change an existing line -> base sign becomes visible
- stage hunk -> second sign replaces base sign
- move down one line and copy paste it (`yyp`) -> issue

The first line has correctly the second sign. The middle/second line hasn't changed/deleted/.. at all but also has the second sign as the line above. The last/third line is shown as a new added line with the according base sign.

I guess it must not be 100% like this, but for some reason this one sign get wrongly placed.

**Comment by weilbith** [comment]
Besides the above issue it works pretty nice. At least for the short test I did. Does what I expected it to do and looks nice. But I did not use any of the change base stuff etc.

**Comment by lewis6991** [comment]
Thanks for the feedback.

The hunk merging is pretty naive and probably needs to be done differently. It currently just compares the signs line-by-line and if they are the same, the sec-sign is removed. I can see why editing a hunk (or adjacent to one) which has been staged would mess this up. Maybe it would be better to compare the hunks instead and only remove the sec-hunk if it matches the main-hunk and if there are any conflicts then show signs for both?

> But I did not use any of the change base stuff etc.

`:Gitsigns chance_sec_base ~` is pretty useful, especially when editing commits during a rebase.

**Comment by weilbith** [comment]
Hey 👋🏾
Any updates on this PR to get merged? `master` gets interesting again. 😬

**Comment by lewis6991** [comment]
Haven't really had time to work on this. It adds quite a lot of complexity and edge case bugs so I'll need to dogfood it for a while yet.

**Pull request closed without merging**
