### PR TITLE
Improve performance on large files

### PR DESCRIPTION
**Pull request by lewis6991**
Added `config.use_decoration_provider` to update signs instead of applying all signs on every update. This is experimental and must explicitly enabled.

### CODE REVIEW

**Comment by lewis6991** [comment]
Just done some more work on this. From my testing everything is a lot faster and comparable to gitgutter. gitgutter is still less laggy in some cases, but that's because it triggers on `CursorHold` whereas gitsigns triggers on something more equivalent to `TextChange` which happens more often.

@seblj @echasnovski. Any change you could try out the latest changes?

**Comment by echasnovski** [comment]
I'll have access tomorrow to the same setup from which I noticed slowdown. I'll try there.

**Comment by seblj** [comment]
I just gave this a go on my file with 99000 lines. I get no lag when navigating around, and the error I reported that I got when moving to the end of file fast, is gone. There is however some lag when typing and adding new lines. It looks like it's equal or a little bit better since last night in this part.

During my testing of typing fast and adding new lines fast to see how much lag there was, I got this message:
image

**Comment by lewis6991** [comment]
That is most definitely due to `update` being called too many times and not finishing quick enough causing the calls to overlap.

Was this with a tracked or untracked file? In my testing untracked files were really quick but I do run a new M1 MacBook which are pretty hard to choke.

**Comment by seblj** [comment]
This was with an untracked file, and I am running NVIM v0.5.0-dev+1102-g595f6e4d6 with iTerm2 Build 3.4.20210226-nightly on a 16 inch Macbook Pro base model. I just pushed my current nvim configuration to github as well. If you would like, I can add the file with 99000 lines to my dotfiles repo for you to test with.

**Comment by lewis6991** [comment]
I can get things to slow down if I crank the line limit to 600k so I can work with that to solve the overlapping update issue.

**Comment by seblj** [comment]
Ok, great! That is a massive amount of lines. Do you not notice any slowing down if you have an untracked file with 100k lines, and type and add new lines really fast?

**Comment by lewis6991** [comment]
> Ok, great! That is a massive amount of lines. Do you not notice any slowing down if you have an untracked file with 100k lines, and type and add new lines really fast?

Nope. The example I created with the `yes` command is pretty smooth. The other example with 600k lines tracked is noticeably slower but not too bad.

**Comment by seblj** [comment]
That's impressive! Please let me know when you have more updates with this, and I would love to test it out. Meanwhile I will be staying on the develop branch to see if I notice anything else

**Comment by echasnovski** [comment]
I tested on big file (around 583000, 28.6 MiB) with current main and e7e0a07. Didn't notice any difference.

Symptoms:
- Around 1-2 seconds freeze between when file is opened and when I can move cursor freely.
- The same slowdown (but not freeze) after editing file in normal mode.
- Very long slowdown when editing file in insert mode. Almost feels like the same slowdown occurs on after every inserted symbol. 
- Very big RAM usage (around 1.3 Gb).

System details:
- Ubuntu: 18.04.
- Git: 2.30.0.
- Neovim: v0.5.0-dev+1062-gcc1851c9f
- Used 'init.vim':
- 
<details><summary>init.vim</summary>

```vim
" auto-install vim-plug
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  "autocmd VimEnter * PlugInstall
  "autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/autoload/plugged')
    Plug 'nvim-lua/plenary.nvim'
    " Plug 'lewis6991/gitsigns.nvim'
    Plug 'lewis6991/gitsigns.nvim', { 'commit': 'e7e0a0768d52bc33c1a8d14e3bde439e33aeb8b2' }
call plug#end()

lua require'gitsigns'.setup { max_file_length = 1000000 }
```

**Comment by lewis6991** [comment]
> I tested on big file (around 583000 lines, 28.6 MiB) with current main and e7e0a07. Didn't notice any difference.

I'm very surprised you didn't notice any difference. How many changes does this file have?

> Around 1-2 seconds freeze between when file is opened and when I can move cursor freely.

Surprised about this too. Whilst testing on a vm, I'm yet to see this. Again maybe your file has too many changes. The performance will scale with the amount of hunks there are. Even though gitsigns (and gitgutter) are asynchronous. Neither are multi-threaded.

I did some more experiments and I believe the underlying thing is that gitgutter uses the `CursorHold` autocommand, whereas gitsigns uses the equivalent of `TextChanged` (with some minor debouncing).

I modified gitsigns to use `CursorHold` and found the performance to be the same or better than gitgutter. For some situations gitgutter was painfully slow, e.g. prepending a space to every line in a tracked file is unusable with gitgutter, whereas this branch of gitsigns could handle it with a bit of lag.

Increasing the debounce time will help, but other than that I'm not sure what else can be done other than using `CursorHold` which results in a worse experience for regular files.

**Comment by seblj** [comment]
Thought I could add a feedback for the develop branch: Yesterday I noticed that all the signs suddenly got removed while typing, and got added back just a second later. Since I do not have signcolumn on all the time, this was a bit annoying, and I later switched back to the main branch. This was on a relatively short file with less than 100 lines. Haven't noticed this issue on the main branch.

**Comment by echasnovski** [comment]
So I tried to do as thorough testing as is reasonable to minimize probability of me making some silly configuration mistake (still possible though :) ).

Steps:
- Created a separate git repository with some big file 'big-file.csv' (600000 lines, 20.5 MiB) and committed it. So any future changes will introduce the only hunks to be displayed.
- Emulated the same sequence of steps with 'gitsigns main', 'gitsigns e7e0a07', and 'gitgutter'. Captured all sequences (prepended with explicitly showing what configuration is used) on video alongside with system monitor and screenkey. Things to look for:
    - Slowdown of Neovim at start (cursor not moving right after pressing 'j').
    - Slowdown of Neovim when typing in insert mode (symbols do not appear at once).
    - Time after making change and signs appearing.
    - CPU and RAM usage.

Link to test with 'gitsigns main': https://streamable.com/ccpmum
Link to test with 'gitsigns e7e0a07': https://streamable.com/2pkbom
Link to test with 'gitgutter': https://streamable.com/i20trm
Link to a file (basically, some random dates and numerical values): https://dropmefiles.com/Alr7u

**Comment by lewis6991** [comment]
Thanks for such a thorough testing @echasnovski .

I did some more comparisons to gitgutter and I think I might have found the main thing causing the performance difference. 

Currently gitsigns sends the buffer text to `git-diff` via a uv pipe to stdin whereas gitgutter just writes the buffer to a temporary file. I 'think' the uv pipe is causing the slowdown so I've opened #77 . Could you give it a go? Note this change doesn't use the decoration provider so there will be a slowdown if there are many signs.

 In my testing with a 600k line file with a few signs the performance was identical to gitgutter. There will probably still be a performance lag when typing quickly but that's purely down to gitsigns using `TextChanged` over `CursorHold`, but I found overall performance to be a lot better.

For untracked files #77 will still be very slow.

**Comment by lewis6991** [comment]
I've just incorporated #77 into the develop branch and made some further tweaks to the decoration provider so you can just try develop.

**Comment by echasnovski** [comment]
Sorry for the long delay. Just tried 6f282d9 and it is much, much better. Definitely around gitgutter in terms of speed and memory usage. As you said, there is still a lag when typing (even at very moderate speed), but it seems to be expected.

Another behavior I experienced is that Neovim sometimes just hangs with 100% CPU usage after typing many characters to a big file. After killing 'nvim' process, there is a message about system error with git. Not sure, it is caused by this new commit, but it definitely happened and most likely due to gitsigns (I repeated the "minimal gitsigns init.vim" setup).

**Comment by echasnovski** [comment]
Yeah, definitely seems more stable. Tried "open-edit-close" cycle couple of times, no hanging with 100% CPU usage.

**Comment by lewis6991** [comment]
In theory it should be really quick as it doesn't need to perform any file IO or launch an external `git diff` process which all introduce bottlenecks.

**Pull request merged**
