### PR TITLE
feat(blame): add verbose render style

### PR DESCRIPTION
**Pull request by iamxiaojianzheng**
image

image

### CODE REVIEW

**Comment by lewis6991** [comment]
What is the point of this?

**Comment by iamxiaojianzheng** [comment]
> What is the point of this?


This might be a better read than the original default. After all, the previous style, there are mismatches. 

I don't think it's very intuitive.

**Comment by iamxiaojianzheng** [comment]
This is an alternative and does not change the default behavior. 

You can switch to this style using parameter control. 

`Gitsigns blame 'verbose'`

**Comment by iamxiaojianzheng** [comment]
The difference looks something like this

image image

**Comment by iamxiaojianzheng** [comment]
I refer to the display effect of `idea`, and I feel that this will indeed be more intuitive.

image

The original way, I think it's a bit of a waste of effort to guess the range of gaps.

**Comment by lewis6991** [comment]
Sorry but I don't want to maintain this, so I think I'll pass.

The current behaviour matches what Github does.

**Comment by iamxiaojianzheng** [comment]
These thick dotted lines feel very affecting reading. After using it for a while, it was a little hard to accept.

image

**Comment by lewis6991** [comment]
Those are defined by your config. Try:

```lua
vim.opt.fillchars:append { diff = ' ' }
```

**Comment by iamxiaojianzheng** [comment]
> Those are defined by your config. Try:
> 
> 
> 
> ```lua
> 
> vim.opt.fillchars:append { diff = ' ' }
> 
> ```

The current display problem is not the character, but the height. No matter what character is changed, even if it is blank, the final effect will interfere with reading.

**Comment by iamxiaojianzheng** [comment]
> Sorry but I don't want to maintain this, so I think I'll pass.
> 
> 
> 
> The current behaviour matches what Github does.
> 
> 
> 
> image
> 
> 

The final effect is also very different from that in the picture.

**Comment by lewis6991** [comment]
One is in a terminal, and the other is in a gui. What changes would you suggest to make it better?

**Comment by iamxiaojianzheng** [comment]
> Looks close enough to me:看起来离我很近：
> 
> image
> 
> One is in a terminal, and the other is in a gui. What changes would you suggest to make it better?一个在终端中，另一个在 gui 中。你建议做出哪些改变来让它变得更好？



> Looks close enough to me:
> 
> image
> 
> One is in a terminal, and the other is in a gui. What changes would you suggest to make it better?

Haha, it doesn't matter what style it is. Just get used to it.

**Pull request closed without merging**
