### PR TITLE
Make popup close on BufLeave

### LINKED ISSUE #296: Popup window does't dissapear when switching buffers
**Describe the bug**
The result of `require("gitsigns").preview_hunk()` doesn't disappear after immediate buffer change.

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/autoload/plugged'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup({debug_mode = true})
EOF

set hidden
```

1. Set up git repository and commit any file. In this example this is file 'init-gitsigns.vim'.
2. Open commited file and make any change.
3. Run `lua require("gitsigns").preview_hunk()` command in changed hunk.
4. Type `:enew`.

**Observed output**
Popup doesn't go anywhere.

**Screenshots**
Gif of the issue:

gitsigns-issue

**Additional context**
System: Ubuntu 18.04
Neovim version: 0.5.0

I managed to resolve this issue by adding `BufLeave` event to [this auto command](https://github.com/lewis6991/gitsigns.nvim/blob/8d284060170bcc96987b3c431a7c8fa3aef9e1cc/lua/gitsigns/popup.lua#L46). If this is a valid solution, happy to make PR.

### PR DESCRIPTION
**Pull request by echasnovski**
Fixes #296.

### CODE REVIEW

**Comment by lewis6991** [comment]
Thanks!

**Comment by echasnovski** [comment]
I am not sure what really happened here, but my commit isn't visible in your repository, but instead it got somehow merged into my fork.

**Comment by lewis6991** [comment]
I've fixed up some incorrect history, you just need to pull, the commit is there.

**Comment by echasnovski** [comment]
I just cloned the entire repository from scratch and 41b6761 is the last commit on 'main' branch. Github also shows that.

**Comment by lewis6991** [comment]
Dam, you're right. Can you redo the PR.

Sorry about this.

**Comment by echasnovski** [comment]
And also the whole history is now different.
Снимок экрана от 2021-08-07 13-30-52

**Comment by lewis6991** [comment]
I rewrote the history to cleanup some errnous commit details, all the commit content is the same, the hashes have just changed. Sorry about that.

**Comment by lewis6991** [comment]
You just need to rebase.

**Pull request merged**
