### PR TITLE
Add support for yadm

### PR DESCRIPTION
**Pull request by lewis6991**

### CODE REVIEW

**Comment by leiserfg** [comment]
Awesome! it works fine. Thanks a lot!

**Comment by clason** [comment]
Sorry for the drive-by comment, but do I understand correctly that this PR lays the groundwork for adding support for other VCS, too (like, say, mercurial)?

**Comment by lewis6991** [comment]
> Sorry for the drive-by comment, but do I understand correctly that this PR lays the groundwork for adding support for other VCS, too (like, say, mercurial)?

Feel free! I appreciate everyones interest and curiosity.

In short, probably not. In long, who knows?

- Yadm is just a git wrapper so any command that gitsigns needs to run is possible in yadm. I'm not totally happy with aspects of this PR, I think I might refactor it so the gitdir is passed into every git command instead of changing the command between `git` or `yadm`.
- Quite a few aspects of gitsigns is moderately coupled to how git works. For example I just merged a change that allows you to stage hunks on files with conflicts (this was suprisingly not that straight forward).
- If support for other VCS's are ever added, it must be done in a way that doesn't limit the cabailities of the git integration. I want gitsigns to be more like to VSCode's GitLens rather than vim/neovim's Signify.
- I don't use any other VCS tools other than git. I used svn on a project a few years back and developed a keen disliking to it so I kinda doubt that will ever be supported (mostly because it needs to constantly talk to a server). Mercurial is more similar to git but I don't know much about it. Either way, it's not something I would individually support, but that doesn't rule out other people supporting it within the project.

With this said, quite a lot of gitsigns is VCS agnostic, and with `config._use_internal_diff` even the diff operation is. Hunk staging is done with patch files. Signs, highlights, job control, async aren't git specific. It's really just `gitsigns.tl` and `gitsigns/git.tl` that contain git specific logic, so there *may* be a possibility to support other VCS in a limited way.

Thanks for the question though. I should probably mention something in the README along the lines of above just so the goals of the project are clear.

**Comment by clason** [comment]
Thanks for the clarification! That makes sense.

> * Yadm is just a git wrapper so any command that gitsigns needs to run is possible in yadm. I'm not totally happy with aspects of this PR, I think I might refactor it so the gitdir is passed into every git command instead of changing the command between `git` or `yadm`.

Ah, I was not aware of this. I guess I jumped to conclusions from the rename of `git.*` to `vcs.*` :)

> * If support for other VCS's are ever added, it must be done in a way that doesn't limit the cabailities of the git integration. I want gitsigns to be more like to VSCode's GitLens rather than vim/neovim's Signify.

Yes, that makes sense (and would indeed be worth mentioning in the README). 

How would you position gitsigns.nvim to vim-fugitive? I think some of the latest additions already go in that direction?

> * I don't use any other VCS tools other than git. I used svn on a project a few years back and developed a keen disliking to it so I kinda doubt that will ever be supported (mostly because it needs to constantly talk to a server). 

Yeah, SVN is dead, and rightly so.

> Mercurial is more similar to git but I don't know much about it. Either way, it's not something I would individually support, but that doesn't rule out other people supporting it within the project.

Some people swear by it as a better alternative to git. If you're used to the git workflow, it's a bit hard to get used to, though (at least for me).
 
So I completely understand not wanting to support it yourself.

> With this said, quite a lot of gitsigns is VCS agnostic, and with `config._use_internal_diff` even the diff operation is. Hunk staging is done with patch files. Signs, highlights, job control, async aren't git specific. It's really just `gitsigns.tl` and `gitsigns/git.tl` that contain git specific logic, so there _may_ be a possibility to support other VCS in a limited way.

That was my initial thought. If gitsigns was limited to diff sign and branch name display, it wouldn't be hard to abstract so many more VCS are supported, but if you add staging (and committing?) to the mix, that changes.

**Comment by clason** [comment]
>  I want gitsigns to be more like to VSCode's GitLens rather than vim/neovim's Signify.

So I expect with the new virtual text features in 0.5, we'll see `git blame` annotations? ;)

**Comment by lewis6991** [comment]
> How would you position gitsigns.nvim to vim-fugitive? I think some of the latest additions already go in that direction?

The way I see it, fugitive is a general purpose interface to git from within vim and does many things but requires you to interact with it and has a relatively steep learning curve IMO.

Gitsigns it much more similar to an LSP. It works in the background and provides decorations and actions about the current buffer and for the most part doesn't actually require much of the user other than to remember a few (but very useful) mappings.

That said, I'm going to add whatever I find useful to gitsigns (because I'm selfish like that) and there are a few things that I use in fugitive that I can imagine adding to gitsigns:
- I often use `:Gread` in fugitive to remove all changes from a buffer. I recently added the mapping `<leader>hR` (function `reset_buffer()`) to replace this (and requires no extra git processes!).
- I also use `:Gblame`/`:Git blame` which is really powerful for traversing history of a file. It's a pretty elaborate feature, but I wouldn't rule it out for gitsigns (especially given how slow it is to use in fugitive).

> So I expect with the new virtual text features in 0.5, we'll see git blame annotations? ;)

Yes. That will be coming. I didn't initially understand why so many people wanted this, I would have thought seeing the blame of a line all the time would be noisy, but after seeing it used in VSCode I now see the attraction.

And also, I don't think there is much code to write in order to implement this. There is already a limited blame action and the groundwork is already there for running git processes. The question is whether it would be better to run a single line blame on every vertical cursor movement or to save the blame for the entire buffer on every buffer update? Or even single line blame on every vertical cursor movement, but cache them, and invalidate the cache on a buffer update. We'll see...

**Comment by clason** [comment]
> The way I see it, fugitive is a general purpose interface to git from within vim and does many things but requires you to interact with it and has a relatively steep learning curve IMO.
> 
> Gitsigns it much more similar to an LSP. It works in the background and provides decorations and actions about the current buffer and for the most part doesn't actually require much of the user other than to remember a few (but very useful) mappings.

Yes, that makes sense. I too find it a bit overwhelming (I pretty much only use `:Gcommit` and `:Gdiff`, and sometimes `:Gpush`), so if I could get by with only gitsigns, I'd be happy.

> That said, I'm going to add whatever I find useful to gitsigns (because I'm selfish like that) and there are a few things that I use in fugitive that I can imagine adding to gitsigns:

> Yes. That will be coming. I didn't initially understand why so many people wanted this, I would have thought seeing the blame of a line all the time would be noisy, but after seeing it used in VSCode I now see the attraction.

To be honest, I very rarely use blame; my comment was mainly motivated by you mentioning Gitlens (which I believe originated as a `git blame` overlay), and how easy that would be now. (Although virtual text _lines_ is still a missing feature.)

(Also, there was https://teukka.tech/vimtip-gitlens.html, which kinda got me started with Lua...)

I think it's definitely something I'd want to toggle on (seldom) and off (most of the time); it's useful to see blame for a range of lines at a time though, to see easily where someone started and stopped messing with the code...

**Comment by leiserfg** [comment]
@lewis6991 `fugitive` `:Gblame` is slow because of the color highlighting, I did this to solve that problem
```vi
let g:fugitive_dynamic_colors = 0
autocmd vimrc FileType fugitiveblame lua require"my/blame_color".highlight_hashes()
```
where 
`blame_color` is 
<https://github.com/leiserfg/dots/blob/master/.config/nvim/lua/my/blame_color.lua>

 feel free to (ab)use it

**Pull request merged**
