### PR TITLE
Configurable blame virtual text position

### PR DESCRIPTION
**Pull request by andersevenrud**
This PR adds a configuration option to adjust the `virt_text_pos` for the git blame virtual text.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Oh, silly me. This is written in Teal.... fixing that.

**Comment by andersevenrud** [comment]
That should be taken care of now.

**Comment by lewis6991** [comment]
LGTM. Thanks a lot.

**Comment by andersevenrud** [comment]
Apparently, the right align option for virtual text does not respect the actual text of the buffer, so if the blame line gets really long it will conceal the text :/ I didn't catch this at first because I only show first name and date with a custom formatter.

Here's an example of what the problem:

2021-06-07-012304_3840x2160_scrot

I'm in the process of finding a solution for this though, but that will probably make this option obsolete.

So maybe revert this commit ?! Sorry about that.

**Comment by andersevenrud** [comment]
I'll probably open an issue in neovim about this, because it would be nice to have an option that actually aligns to the right but also crops the text so that there's no overlap.

**Comment by lewis6991** [comment]
Yeah maybe it is worth reverting.

**Pull request merged**
