### PR TITLE
FFI: Recycle hunk_func (again)

### PR DESCRIPTION
**Pull request by lewis6991**
- Added missing unused argument to the callback. Maybe this was the
  issue?
- Avoid table.insert, apparently this is slow in lua.
- Make sure to nil hunk_results when we are done with it an initialise
  it when we need it again.

### CODE REVIEW

**Comment by oberblastmeister** [comment]
you could also consider using plenary list, which keeps track of size and is faster

**Comment by lewis6991** [comment]
Interesting. Why exactly is it faster?

**Comment by oberblastmeister** [comment]
luajit does not compile `table.insert` so you have to manually set an index using the length of the table. Plenary list keeps track of the size so it is like manually setting the index but with a nicer interface.

**Comment by lewis6991** [comment]
I would have imagined something like luajit would keep track of indices of tables being inserted around tight loops, but from what I can tell you're right and it doesn't.

I did notice that the imp for `List:push` is only faster if your running luajit built with 5.2compat since 5.1 doesn't have the `__len` metamethod. So unless I'm missing something, we should probably tweak it to use the length it tracks:

```lua
function List:push(other)
  -- self[#self + 1] = other
  self[self._len + 1] = other
  self._len = self._len + 1
end
```

**Comment by oberblastmeister** [comment]
yes we should definitely do that

**Pull request closed without merging**
